version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.4-jessie-node
        environment:
          # TODO needed?
          CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
          MOCHA_FILE: /tmp/circleci-test-results/mocha.xml
          DATABASE_URL: mysql2://root:very-secret@mysql/sharetribe_test
          NODE_VERSION: 7.8.0
          NODE_ENV: test
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD=very-secret
    steps:
      - checkout
      - run:
          name: install deps
          command: script/ci-install-deps.sh
      - restore_cache:
          key: deps-cache
      - run:
          name: bundle install
          command: bundle check --path=vendor/bundle || bundle install --without=development
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: deps-cache
          paths:
            - vendor/bundle
            - ~/.bundle
            - client/node_modules
            - ./node_modules
      - run:
          name: prepare
          command: script/ci-prepare.sh
      - run:
          name: rubocop
          command: bundle exec rubocop -R
      - run:
          name: npm lint
          command: source ~/.nvm/nvm.sh && npm run link
          working_directory: client
      - run:
          name: rspec
          command: bundle exec rspec --format progress --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec.xml:
workflows:
  version: 2
  test:
    jobs:
      - test
