version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.4-jessie-node
        environment:
          # TODO needed?
          MOCHA_FILE: /tmp/circleci-test-results/mocha.xml
          DATABASE_URL: mysql2://root:very-secret@mysql/sharetribe_test
          NODE_VERSION: 7.8.0
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD=very-secret
    steps:
      - checkout
      - run:
          name: install deps
          command: script/ci-install-deps.sh
      - run:
          name: rebuild node-sass
          command: source .nvm/nvm.sh && cd client && npm rebuild node-sass
workflows:
  version: 2
  test:
    jobs:
      - test
