version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.4-node
      environment:
        # TODO needed?
        MOCHA_FILE: /tmp/circleci-test-results/mocha.xml
        DATABASE_URL=mysql2://root:very-secret@mysql/sharetribe_test
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD=very-secret
    steps:
      - checkout
      - run:
          name: install sphinxsearch
          command: add-apt-repository -y ppa:builds/sphinxsearch-rel22
workflows:
  version: 2
  test:
    jobs:
      - test
